name: EternalDeathChests
main: xyz.oribuin.deathchests.EternalDeathChests
version: '1.0'
api-version: '1.16'
author: Oribuin
description: A deathchest alternative created to load up the spigot plugin aresenal.
softdepend:
  - PlaceholderAPI
  - HolographicDisplays
  - CMI
  - Holograms
  - GHolo